const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;

export const TIME_CONSTANTS = {
  SECOND,
  FOUR_HUNDRED_MILLISECONDS: 400,
  TEN_SECONDS: 10 * SECOND,
  THIRTY_SECONDS: 30 * SECOND,
  FIFTY_SECONDS: 50 * SECOND,

  MINUTE: MINUTE,
  TWO_MINUTES: 2 * MINUTE,
  THREE_MINUTES: 3 * MINUTE,
  FIVE_MINUTES: 5 * MINUTE,
  TEN_MINUTES: 10 * MINUTE,
  FIFTEEN_MINUTES: 15 * MINUTE,
  THIRTY_MINUTES: 30 * MINUTE,

  HOUR: HOUR,
  TWO_HOURS: 2 * HOUR,

  DAY: 24 * HOUR,
  SEVEN_DAYS: 7 * 24 * HOUR,
  THIRTY_DAYS: 30 * 24 * HOUR,
} as const;
